before_script:
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - production

prod_deploy:
  stage: production
  script:
    - ssh $SSH_USERNAME_PROD@$SSH_HOST_PROD "cd $BE_ROOT_PATH
      && git reset --hard HEAD && git checkout master
      && git pull origin master
      && DOCKER_USER=1000:1000 docker-compose -f "docker/docker-compose.yml" up -d
      && exit
      "
  only:
    - master
