image: php:7.4

services:
  - redis:6-alpine

before_script:
  - bash docker/ci/install.sh > /dev/null
  - curl -sS https://getcomposer.org/installer | php
  - ./composer.phar install

cache:
  paths:
    - vendor/

stages:
  - test
  - deploy

variables:
  REDIS_PORT: 6379
  REDIS_HOST: redis

phpunit:
  stage: test
  script:
    - php artisan key:generate
    - php vendor/bin/phpunit

deploy_production:
  stage: deploy
  script:
    - ssh $SSH_USERNAME_PROD@$SSH_HOST_PROD "cd $BE_ROOT_PATH
      && git reset --hard HEAD && git checkout master
      && git pull origin master
      && docker run --rm --interactive --volume $BE_ROOT_PATH:/app composer install --ignore-platform-reqs --no-scripts
      && docker-compose -f "docker/docker-compose.yml" pull
      && DOCKER_USER=1000:1000 docker-compose -f "docker/docker-compose.yml" up -d --build
      && docker exec -u 1000:1000 poker_php php artisan cache:clear
      && docker exec -u 1000:1000 poker_php php artisan route:cache
      && docker exec -u 1000:1000 poker_php php artisan config:clear
      && docker exec -u 1000:1000 poker_php php artisan view:cache
      && exit"
  only:
    - master
