image: php:7.4

before_script:
  - bash docker/ci/install.sh > /dev/null
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('sha384', 'composer-setup.php') === 'c31c1e292ad7be5f49291169c0ac8f683499edddcfd4e42232982d0fd193004208a58ff6f353fde0012d35fdd72bc394') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - ./composer.phar install

cache:
  paths:
    - vendor/

#stages:
#  - test
#
#phpunit:
#  stage: test
#  script:
#    - php vendor/bin/phpunit
