image: php:7.4

services:
  - redis:6-alpine

before_script:
  - bash docker/ci/install.sh > /dev/null
  - curl -sS https://getcomposer.org/installer | php
  - ./composer.phar install

cache:
  paths:
    - vendor/

stages:
  - test

phpunit:
  stage: test
  script:
    - php artisan key:generate
    - php vendor/bin/phpunit --configuration phpunit.ci.xml
